/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.io.*;
import java.awt.*;
import javax.swing.*;
import menu.StudentMenu;
import menu.SAdminMenu;
import menu.ProfessorMenu;
import menu.HAdminMenu;
/**
 *
 * @author dbswl
 */
public class Login extends javax.swing.JFrame  {
    Container cPane;
    ImageIcon img; // 이미지
    JLabel ImgBox; // 이미지
    String id; // 아이디
    String pass ; // 비밀번호
    String str; // 사용자의 정보
    static public StudentMenu smenu;
    static public ProfessorMenu pmenu;
    static public HAdminMenu hmenu;
    static public SAdminMenu samenu;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        showimage(); // 동의대학교 마크를 보여준다
        setTitle("대학관리시스템");
        setSize(400,400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        setResizable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("나눔고딕", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("나눔고딕", 0, 12)); // NOI18N
        jLabel2.setText("PASSWD");

        jButton1.setFont(new java.awt.Font("나눔고딕", 0, 14)); // NOI18N
        jButton1.setText("로그인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("나눔고딕", 1, 24)); // NOI18N
        jLabel3.setText("대학관리시스템");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pushlogin();   
    }//GEN-LAST:event_jButton1ActionPerformed
    public void showimage(){ //동의대학교 마크를 보여준다
          cPane = getContentPane();
        cPane.setLayout(null);
        img = new ImageIcon("image\\mark.png"); 
        ImgBox = new JLabel(img);
        ImgBox.setBounds(0,0,400,300);
        cPane.add(ImgBox);
    }
    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //Login n = new Login();
        /* Create and display the form */
         Login n = new Login(); 
        smenu = new StudentMenu();
        pmenu = new ProfessorMenu();
        hmenu = new HAdminMenu();
        samenu = new SAdminMenu();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    public void pushlogin(){ // 입력된 정보들을 구분한다.

        id = jTextField1.getText();
        pass = jPasswordField1.getText();
        str = id+"/"+pass;
        
        String[] array;
        char ch;
        try{
            File myFile = new File("DB\\information.txt"); // 사용자의 정보를 읽는다.
            FileReader fileReader = new FileReader(myFile);
            BufferedReader reader = new BufferedReader(fileReader);
            if(jTextField1.getText().length() == 0 || jPasswordField1.getText().length() == 0 ){ // 만약 입력하지않았다면 경고문과 로그인 취소
                JOptionPane.showMessageDialog(null,"아이디또는 비밀번호를 입력 하셔야 됩니다","아이디나 비밀번호를 입력!",JOptionPane.DEFAULT_OPTION);
                 return;
       }            
            String line = null;
            int i = 0;
            while((line = reader.readLine()) != null){ // information.txt파일에 정보가 있는지를 확인한다.
                array = line.split("/"); 
                String idp = array[0] + "/" + array[1];
                if(idp.equals(str)){ //입력한 아이디와 비밀번호와 일치한다면 맞는 메뉴에 접속하게 된다.
                   
                    ch = line.charAt(0); // 학생 교수 학사 담당자 수업 담당자 중 누구인지 파악하기위해 아이디의 첫 글자를 저장한다.
                    if(ch == 'S'){
                        // 학생
                         
                         smenu.visible(i);
                        dispose();
                    }
                    
                    if(ch == 'P'){
                           // 교수
                            pmenu.visible(i);
                            dispose();
                    }
                    
                    if(ch == 'H'){
                              // 학사 담당자
                              hmenu.visible(i);
                               dispose();
                    }
                      
                    if(ch == 'G'){
                          // 수업 담당자
                          
                          dispose();
                    }
                        
                    return;
               
                }
                i += 1;
            }
                
            reader.close();
        } catch(Exception ex){
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "로그인 실패", "로그인 확인!", JOptionPane.DEFAULT_OPTION); // 로그인 실패
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}
